spring:
  application:
    name: e_commerce
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    # 1. Added ?sslmode=require to enforce the secure cloud database handshake
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ecommerce_db_sgpq}?sslmode=require
    driver-class-name: org.postgresql.Driver
    # 2. Instructs HikariCP to try connecting for up to 30 seconds before crashing the app context
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

paystack:
  base-url: https://paystack.co
  secret-key: sk_test_d7dcccfaf6e1c4cc9e94b684c7b4c527f858c236
app:
  admin:
    email: admin@gmial.com
    password: adminPass
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.access: TRACE
